DROP TABLE IF EXISTS tasks cascade;

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(500),
    creation_on TIMESTAMP WITHOUT TIME ZONE,
    creation_on_updated TIMESTAMP WITHOUT TIME ZONE,
    status SMALLINT
);